// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CourseOnlineDbContext))]
    partial class CourseOnlineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Addresses.ClassLocationAddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("ClassLocationAddresses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Class_Location_Address_Dates", "[ModifiedAt] >= [CreatedAt]");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Addresses.ProfileAddressEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("ProfileAddresses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Profile_Address_Dates", "[ModifiedAt] >= [CreatedAt]");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Categories.CategoryCourseEntity", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryCourses", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Categories.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categoriy_Dates", "[ModifiedAt] >= [CreatedAt]");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Classes.ClassCourseEventEntity", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseEventId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClassId", "CourseEventId");

                    b.HasIndex("CourseEventId");

                    b.ToTable("ClassCourseEvents", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Classes.ClassEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassLocationId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ProgramId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassLocationId");

                    b.HasIndex("Name");

                    b.HasIndex("ProgramId");

                    b.ToTable("Classes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Class_Dates", "[ModifiedAt] >= [CreatedAt]");

                            t.HasCheckConstraint("CK_Seat_Min", "[Seats] >= 0");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Classes.ClassLocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassLocationAddressId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ClassLocationAddressId");

                    b.ToTable("ClassLocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Class_Locations_Dates", "[ModifiedAt] >= [CreatedAt]");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Classes.ClassProfileEntity", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClassId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ClassProfiles", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Courses.CourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Courses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Course_Dates", "[ModifiedAt] >= [CreatedAt]");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Courses.CourseEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("EventLocationId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("EventLocationId");

                    b.ToTable("CourseEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_Course_Event_Dates", "[ModifiedAt] >= [CreatedAt]");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Courses.CourseProfileEntity", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfileId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseId", "ProfileId");

                    b.HasIndex("ProfileId");

                    b.ToTable("CourseProfiles", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Courses.EventLocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("EventLocations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Event_Location_Dates", "[ModifiedAt] >= [CreatedAt]");

                            t.HasCheckConstraint("CK_Seat_Min", "[Seats] >= 0")
                                .HasName("CK_Seat_Min1");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Role_Dates", "[ModifiedAt] >= [CreatedAt]");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.ProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .IsUnicode(false)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirstName", "LastName");

                    b.ToTable("Profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Profiles_Dates", "[ModifiedAt] >= [CreatedAt]");

                            t.HasCheckConstraint("CK_Profiles_Email_NotEmpty", "LEN([Email]) > 0");

                            t.HasCheckConstraint("CK_Profiles_PhoneNumber_NotEmpty", "[PhoneNumber] IS NULL OR LEN([PhoneNumber]) > 0");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Programs.CourseProgramEntity", b =>
                {
                    b.Property<Guid>("ProgramId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProgramId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CoursePrograms", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Programs.ProgramEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Programs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Program_Dates", "[ModifiedAt] >= [CreatedAt]");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Roles.ProfileRoleEntity", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProfileId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("ProfileRoles", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Roles.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", null, t =>
                        {
                            t.HasCheckConstraint("CK_Role_Dates", "[ModifiedAt] >= [CreatedAt]")
                                .HasName("CK_Role_Dates1");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Roles.RolePermissionEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasMaxLength(68)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Addresses.ClassLocationAddressEntity", b =>
                {
                    b.OwnsOne("Domain.Models.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ClassLocationAddressEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.HasKey("ClassLocationAddressEntityId");

                            b1.ToTable("ClassLocationAddresses");

                            b1.WithOwner()
                                .HasForeignKey("ClassLocationAddressEntityId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Addresses.ProfileAddressEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Models.Entities.ProfileEntity", "Profile")
                        .WithOne("Address")
                        .HasForeignKey("Infrastructure.Persistence.Models.Entities.Addresses.ProfileAddressEntity", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Models.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ProfileAddressEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.HasKey("ProfileAddressEntityId");

                            b1.ToTable("ProfileAddresses");

                            b1.WithOwner()
                                .HasForeignKey("ProfileAddressEntityId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Categories.CategoryCourseEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Models.Entities.Categories.CategoryEntity", "Category")
                        .WithMany("CategoryCourses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Models.Entities.Courses.CourseEntity", "Course")
                        .WithMany("CategoryCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Classes.ClassCourseEventEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Models.Entities.Classes.ClassEntity", "Class")
                        .WithMany("ClassCourseEvents")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Models.Entities.Courses.CourseEventEntity", "CourseEvent")
                        .WithMany("ClassCourseEvents")
                        .HasForeignKey("CourseEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("CourseEvent");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Classes.ClassEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Models.Entities.Classes.ClassLocationEntity", "ClassLocation")
                        .WithMany("Classes")
                        .HasForeignKey("ClassLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Models.Entities.Programs.ProgramEntity", "Program")
                        .WithMany("Classes")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassLocation");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Classes.ClassLocationEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Models.Entities.Addresses.ClassLocationAddressEntity", "ClassLocationAddress")
                        .WithMany("ClassLocations")
                        .HasForeignKey("ClassLocationAddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassLocationAddress");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Classes.ClassProfileEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Models.Entities.Classes.ClassEntity", "Class")
                        .WithMany("ClassProfiles")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Models.Entities.ProfileEntity", "Profile")
                        .WithMany("ClassProfiles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Courses.CourseEventEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Models.Entities.Courses.CourseEntity", "Course")
                        .WithMany("CourseEvents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Models.Entities.Courses.EventLocationEntity", "EventLocation")
                        .WithMany("CourseEvents")
                        .HasForeignKey("EventLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("EventLocation");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Courses.CourseProfileEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Models.Entities.Courses.CourseEntity", "Course")
                        .WithMany("CourseProfiles")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Models.Entities.ProfileEntity", "Profile")
                        .WithMany("CourseProfiles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Programs.CourseProgramEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Models.Entities.Courses.CourseEntity", "Course")
                        .WithMany("CoursePrograms")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Models.Entities.Programs.ProgramEntity", "Program")
                        .WithMany("CoursePrograms")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Programs.ProgramEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Models.Entities.Categories.CategoryEntity", "Category")
                        .WithMany("Programs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Roles.ProfileRoleEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Models.Entities.ProfileEntity", "Profile")
                        .WithMany("ProfileRoles")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Models.Entities.Roles.RoleEntity", "Role")
                        .WithMany("ProfileRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Roles.RolePermissionEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Models.Entities.PermissionEntity", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Models.Entities.Roles.RoleEntity", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Addresses.ClassLocationAddressEntity", b =>
                {
                    b.Navigation("ClassLocations");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Categories.CategoryEntity", b =>
                {
                    b.Navigation("CategoryCourses");

                    b.Navigation("Programs");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Classes.ClassEntity", b =>
                {
                    b.Navigation("ClassCourseEvents");

                    b.Navigation("ClassProfiles");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Classes.ClassLocationEntity", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Courses.CourseEntity", b =>
                {
                    b.Navigation("CategoryCourses");

                    b.Navigation("CourseEvents");

                    b.Navigation("CourseProfiles");

                    b.Navigation("CoursePrograms");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Courses.CourseEventEntity", b =>
                {
                    b.Navigation("ClassCourseEvents");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Courses.EventLocationEntity", b =>
                {
                    b.Navigation("CourseEvents");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.PermissionEntity", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.ProfileEntity", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("ClassProfiles");

                    b.Navigation("CourseProfiles");

                    b.Navigation("ProfileRoles");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Programs.ProgramEntity", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("CoursePrograms");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Models.Entities.Roles.RoleEntity", b =>
                {
                    b.Navigation("ProfileRoles");

                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
